"""ID de los botones de la plataforma de consulta amigable"""

NIVEL_GOBIERNO = "ctl00$CPH1$BtnTipoGobierno"
GENERICA = "ctl00$CPH1$BtnGenerica"
SUB_GENERICA = "ctl00$CPH1$BtnSubGenerica"
DETALLE_SUB_GENERICA = "ctl00$CPH1$BtnSubGenericaDetalle"
ESPECIFICA = "ctl00$CPH1$BtnEspecifica"
DETALLE_ESPECIFICA = "ctl00$CPH1$BtnEspecificaDetalle"
MES = "ctl00$CPH1$BtnMes"
DEPARTAMENTO = "ctl00$CPH1$BtnDepartamento"
DEPARTAMENTO_META = "ctl00$CPH1$BtnDepartamentoMeta"
MUNICIPALIDAD = "ctl00$CPH1$BtnMunicipalidad"
FUNCION = "ctl00$CPH1$BtnFuncion"
FUENTE = "ctl00$CPH1$BtnFuenteAgregada"
RUBRO = "ctl00$CPH1$BtnRubro"
PROGRAMA_PARTICIPATIVO = "ctl00$CPH1$BtnProgramaPpto"
PROGRAMA_PPTO = "ctl00$CPH1$BtnProgramaPpto"
ACTIVIDAD_PROYECTO = "ctl00$CPH1$BtnActProy"
PROGRAMA = "ctl00$CPH1$BtnPrograma"
SUB_PROGRAMA = "ctl00$CPH1$BtnSubPrograma"
TRIMESTRE = "ctl00$CPH1$BtnTrimestre"

# adicionales
SUB_TIPO_GOBIERNO = "ctl00$CPH1$BtnSubTipoGobierno"
GOB_LOCALES_MANCOMUNIDADES = "ctl00$CPH1$BtnSubTipoGobierno"
CATEGORIA_PRESUPUESTAL = "ctl00$CPH1$BtnProgramaPpto"
PRODUCTO_PROYECTO = "ctl00$CPH1$BtnProdProy"
ACTIVIDAD_ACCION = "ctl00$CPH1$BtnAAO"
